Lab on threads
Nastya31/new_git pull request #3
Opened 2023-10-09 18:34 UTC by Nastya31

2023-11-11 09:26 UTC, GrandpaKaseki reviewed
В целом, всё правильно и хорошо! Пара придирок по оформлению

2023-11-11 09:26 UTC, GrandpaKaseki commented on threadss.py
> +        time.sleep(2)
По заданию надо собирать метрику раз в 60 сек, а не раз в 2 сек

2023-11-11 09:26 UTC, GrandpaKaseki commented on threadss.py
> +        time.sleep(2)
Тут тоже

2023-11-11 09:26 UTC, GrandpaKaseki commented on threadss.py
> +work_time = 15
Константные значение по PEP8 (это типо правила оформления python кода) называются капсом WORK_TIME

2023-11-13 13:33 UTC, Crocussys commented on threadss.py
> +work_time = 15
И в начале файла

2023-11-13 13:40 UTC, Crocussys requested changes
Traceback (most recent call last):
  File "D:\Repositories\new_git\threadss.py", line 3, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

Надо почистить репозиторий от лишних файлов + обновить requirements.txt

2023-11-13 13:40 UTC, Crocussys commented on threadss.py
> +work_time = 15
А если неизвестно сколько надо собирать?

2023-11-13 13:40 UTC, Crocussys commented on threadss.py
> +        time.sleep(2)
Ну кста да. С двумя секундами ладно, а вот с 60ю могут начаться проблемы при выходе из проги

2023-11-26 14:55 UTC, merged